# Generated by Django 2.1.7 on 2019-04-01 14:52

import connect_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('crn', models.IntegerField(default=0, primary_key=True, serialize=False, validators=[connect_app.validators.valid_crn])),
                ('title', models.CharField(default='Title', max_length=50)),
                ('course_number', models.CharField(default='Major XXX', max_length=10)),
                ('section_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('netId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='connect_app.Student'),
        ),
    ]
